### ISSUE TITLE
can't find cv_bridge

### ISSUE THREAD

**Issue by Richardcvpr** [ZKangsen/dsm_ros#1]
when i  run the cmd ./build_ros.sh,  the error happened:

[  0%] Built target rospack_genmsg_libexe
[  0%] Built target rosbuild_precompile
[ 50%] Building CXX object CMakeFiles/ros_mono1.dir/main.cpp.o
[100%] Linking CXX executable /home/jinweihu/project/DSM/dsm_ros-main/ROS_Examples/ros_mono/ros_mono1
c++: error: cv_bridge: No such file or directory

but i have given the dir of cv_bridge path in the cmakelist file , i don't know what happend,please help me, Thanks!

**Comment by ZKangsen** [comment]
Check if the path exists:  /opt/ros/melodic/include/cv_bridge   (note: melodic -> ubuntu18.04)
if not exists:  sudo apt-get install ros-melodic-cv-bridge
